print("Hello, this is a game of mad lib, enjoy!".upper())
adjective = input("\nEnter an adjective: ")
noun = input("Enter a noun: ")
plural_noun = input("Enter a plural noun: ")
noun0 = input("Enter another noun: ")
adjective0 = input("Enter another adjective: ")
past_verb = input("Enter a verb in past tense: ")
noun1 = input("Enter another noun: ")
noun2 = input("Enter another noun: ")
adjective1 = input("Enter another adjective: ")
plural_noun0 = input("Enter another plural noun: ")
print("\n\n\nHere are some of the " + adjective + " phrases you might, unfortunately, remember hearing from your mother's " + noun + ":")
print("\n\"Well, if the other " + plural_noun + " jumped out off a " + noun0 + ", would you do it, too?!\"")
print("\n\"Always wear " + adjective0 + " underwear in case you are in an accident.\"")
print("\n\"I never " + past_verb + " when I was your age.\"")
print("\n\"Dont sit so close to the " + noun1 + " you will go blind!\"")
print("\n\"Put on a warm " + noun2 + " or you will catch cold!\"")
print("\nOh, well. I guess when I'm older, I will impart the same " + adjective1 + " wisdom to my young " + plural_noun0 + ".")